### ISSUE TITLE
NPM libe - Palette Package erro

### ISSUE THREAD

**Issue by edniltonmatos** [andremalveira/palette#1]
O último bloco de código desse popup está quebrando o design da página. Adicionei uma imagem abaixo para ilustrar o que está acontecendo. 

Espero que te ajude. ótimo projeto, parabéns😁

![disign-quebrado](https://user-images.githubusercontent.com/96772358/213439269-43d39c68-6e1a-47ec-abd3-b731e78da7e7.png)

**Comment by andremalveira** [comment]
Obrigado por informar o problema 👍😁, corrigido!
